# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1738114414c31fd267b6f4566c71201b116a86880e21639d364406b4a9eac571f4532b6bd1ad0e6089510e03cf073cd4eb767ea66d1ff611dc0b7894e83987e7

test:
  secret_key_base: b6a9ee2b38be4479461f2f8ef71664c12e84bb43e52e69025ee6d0588801e45ebaf4a92a4c3cee54e61d3dc8b3981e3a8d1594df5c40c5e48a48c2f20b45d923

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
